config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/help", to: "static_pages#help"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users, except: %(new create)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
end

app/models/booking_detail.rb
class BookingDetail < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  enum status: [:now_showing, :comming_soon]
end

app/models/payment.rb
class Payment < ApplicationRecord
end

app/models/promotion.rb
class Promotion < ApplicationRecord
end

app/models/ratting.rb
class Ratting < ApplicationRecord
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/schedule.rb
class Schedule < ApplicationRecord
end

app/models/seat.rb
class Seat < ApplicationRecord
end

app/models/theater.rb
class Theater < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: Settings.val_name_max }
  validates :email, presence: true, length: { maximum: Settings.val_email_max },
                    format: { with: Settings.email_regex },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true,
                       length: { minimum: Settings.val_pass_min },
                       allow_nil: true
  validates :phone, presence: true, length: { maximum: Settings.val_phone_max },
                    format: { with: Settings.phone_regex }
  before_save :email_downcase
  has_secure_password
  enum role: {user: 0, admin: 1}

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create string, cost: cost
  end

  private

  def email_downcase
    email.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  protect_from_forgery with: :exception
  include SessionsHelper

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path
    else
      flash.now[:danger] = t ".noti_invalid"
      render :new
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home;end

  def help;end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:show, :edit, :update]
  before_action :load_user, only: [:show, :edit, :update]

  def show
    return if @user

    flash[:danger] = t ".fail_show"
    redirect_to root_path
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t ".success_create"
      redirect_to root_path
    else
      render :new
    end
  end

  def edit;end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = t ".flash_update"
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
                                 :password_confirmation, :phone, :gender,
                                 :birthday, :city
  end

  def logged_in_user
    return if logged_in?

    flash[:danger] = t ".flash_login"
    redirect_to login_url
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t ".flash_load_user"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "title"
    page_title.blank? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
      @current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def log_out
    session.delete :user_id
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="row footer-top">
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
      <ul class="list-unstyled clear-margins">
        <li class="widget-container widget_nav_menu">
          <h4 class="title-widget">
            <%= t "footer.introduce"%>
          </h4>
          <ul>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.about_us" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.team_of_use" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.openrating" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.privacy_police" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
      <ul class="list-unstyled clear-margins">
        <li class="widget-container widget_nav_menu">
          <h4 class="title-widget">
            <%= t "footer.cinema_blog"%>
          </h4>
          <ul>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.movie_genre" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.movie_review" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.movie_blog" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.hot_movie" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
      <ul class="list-unstyled clear-margins">
        <li class="widget-container widget_nav_menu">
          <h4 class="title-widget">
            <%= t "footer.support"%>
          </h4>
          <ul>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.feedback" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.sale_service" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.cinema_ticket" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <%= t "footer.career" %> <i class="fa fa-angle-right"></i>
              <% end %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-6">
      <ul class="list-unstyled clear-margins">
        <li class="widget-container widget_recent_news">
          <h4 class="title-widget">
            <%= t "footer.contact"%>
          </h4>
          <div class="social-icons">
            <ul class="nomargin">
              <a href=""><i class="fa fa-facebook-square"></i></a>
              <a href=""><i class="fa fa-twitter"></i></a>
              <a href=""><i class="fa fa-youtube"></i></a>
              <a href=""><i class="fab fa-instagram-square"></i></a>
            </ul>
          </div>
        </li>
      </ul>
    </div>
  </div>
  <div class="row footer-bottom">
    <div class="container-fluid">
      <p><%= t "footer.coppyright"%><br><%= t "footer.bot"%></p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container-fluid">
    <%= link_to t("header.booking"), root_path, id: "logo" %>
    <%= form_tag url: "#", method: :get do %>
      <div class="search col-xs-6 col-md-4">
        <div class="input-group">
          <%= text_field_tag :search, params[:search],
           placeholder: t("header.search"), :class =>"form-control" %>
          <div class="input-group-btn">
            <%= button_tag(:class =>"btn") do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li class="menu"><%= link_to t("header.movies"),  root_path %></li>
        <li class="menu"><%= link_to t("header.theaters"),  help_path %></li>
        <li class="menu"><%= link_to t("header.news"), "#" %></li>
        <li class="menu">
          <li class="dropdown">
              <%= link_to '#', class: "dropdown-toggle",
               data: {toggle: "dropdown"} do %>
                <i class="fa fa-user"></i>
                <b class="caret"></b>
              <% end %>
            <ul class="dropdown-menu">
              <% if logged_in? %>
                <li>
                  <%= link_to t(".profile"), edit_user_path(current_user) %>
                </li>
                <li>
                  <%= link_to t(".change_pass"), "#" %>
                </li>
                <li class="divider"></li>
                <li>
                 <%= link_to t(".log_out"), logout_path, method: :delete %>
                </li>
              <% else %>
                <li><%= link_to t(".login"), login_path %></li>
              <% end %>
            </ul>
          </li>
        </li>
        <li class="language">
          <%= link_to t("english"), locale: "en" %>
          <%= link_to t("vietnam"), locale: "vi" %>
        </li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all",
     "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
    <%= render "layouts/shim" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t(".content", size: @user.errors.size) %>
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<% provide :title, t(".title") %>
<h1><%= t ".caption" %></h1>

app/views/static_pages/home.html.erb
<% provide :title, t(".title") %>
<div class="center jumbotron">
  <h1><%= t ".caption" %></h1>
</div>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= render "shared/error_messages" %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
  </div>
  <div class="form-row">
    <div class="col-md-6">
      <%= f.label :phone %>
      <%= f.telephone_field :phone, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :city %>
      <%= f.text_field :city, class: "form-control" %>
    </div>
      </div>
  <div class="form-row">
    <div class="col-md-6">
      <%= f.label :birthday %>
      <%= f.date_field :birthday, class: "form-control" %>
    </div>
    <div class="col-md-6">
      <%= f.label :gender %>
      <div class="form-group">
        <%= f.label :gender, class: "d-block" do %>
          <%= f.radio_button :gender, "male" %>
          <%= t (".male") %>
        <% end %>
        <%= f.label :gender, class: "d-block" do %>
          <%= f.radio_button :gender, "female" %>
          <%= t (".female") %>
        <% end %>
      </div>
    </div>
  </div>
  <%= f.submit yield(:button_text), class: "btn btn-warning" %>
<% end %>

app/views/users/edit.html.erb
<% provide :title, t(".profile") %>
<% provide :button_text, t(".save_changes") %>
<h1><%= t ".profile" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/users/new.html.erb
<% provide :title, t(".sign_up") %>
<% provide :button_text, t(".create") %>
<h1><%= t ".sign_up" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>